### PR TITLE
fix(lib/expo_router_plugin): closing modal when navigating through ide panel

### PR DESCRIPTION
**Pull request by kewinzaq1**
The problem: 

https://github.com/software-mansion/react-native-ide/assets/77052270/5b26f4cb-24cf-4c13-a57d-f33f9a20d680

More info:
image

### CODE REVIEW

**Comment by kewinzaq1** [comment]
@patrycjakalinska Hi what is this issue closed?

**Comment by kewinzaq1** [comment]
@patrycjakalinska Why is this issue closed?

**Comment by patrycjakalinska** [comment]
@kewinzaq1 Sorry for this inconvenience, this shouldn't had been closed - reopening it now :)

**Comment by kmagiera** [comment]
Hi @kewinzaq1 – apparently we 're unable to re-open the PR. It is likely because your fork is private since it's been forked while the repo was still private. If you could make your fork public I believe we should be able to bring it back

**Comment by kewinzaq1** [comment]
HI @kmagiera now it's public

**Comment by kmagiera** [comment]
I'm sorry @kewinzaq1 but it seems like something is messed up on GitHub here. Every time I click re-open it immediately closes. Would you be able to open new PR with this?

**Comment by kewinzaq1** [comment]
@kmagiera https://github.com/software-mansion/react-native-ide/pull/316

**Pull request closed without merging**
